import Foundation
import XCTest

@testable import FluidAudio

/// Runs the blank-gap VAD repair against all 536 eval recording audio files and
/// writes a comparison JSON to /tmp/repair_comparison.json.
///
/// Run with:
///   cd FluidAudio && swift test --filter EvalHistoryRepairTests
///
/// Requires /tmp/eval_manifest_index.json (generated by the Python helper script).
final class EvalHistoryRepairTests: XCTestCase {

    private static let manifestPath = "/tmp/eval_manifest_index.json"
    private static let outputPath = "/tmp/repair_comparison.json"

    // Store ALL gaps regardless of size — viewer applies threshold interactively
    private static let gapThresholdFrames = 4  // wide net; viewer filters by gap size
    private static let frameSeconds = 0.08
    private static let samplesPerFrame = 1280  // 80ms @ 16kHz

    func testRepairAgainstEvalHistory() async throws {
        guard FileManager.default.fileExists(atPath: Self.manifestPath) else {
            throw XCTSkip("Run the Python manifest indexer first: /tmp/eval_manifest_index.json not found")
        }

        // ── Load manifest ────────────────────────────────────────────────
        let manifestData = try Data(contentsOf: URL(fileURLWithPath: Self.manifestPath))
        let allEntries = try JSONSerialization.jsonObject(with: manifestData) as! [[String: Any]]
        print("Loaded \(allEntries.count) manifest entries")

        // ── Load models once ─────────────────────────────────────────────
        let tdtModels = try await AsrModels.loadFromCache()
        let manager = AsrManager()
        try await manager.initialize(models: tdtModels)
        let vocab = manager.vocabulary

        let vad = try await VadManager()
        let chunkDuration = Double(VadManager.chunkSize) / 16000.0  // 0.256s

        let converter = AudioConverter()

        // ── Per-entry pipeline ───────────────────────────────────────────
        var results: [[String: Any]] = []
        var changed = 0
        var repairFired = 0
        var errors = 0

        for (i, entry) in allEntries.enumerated() {
            let idx = entry["index"] as? Int ?? i
            let audioPath = entry["_audio_abs"] as? String ?? ""
            let rawSTT = entry["rawSTT"] as? String ?? ""
            let expected = entry["expected"] as? String ?? ""
            let category = entry["category"] as? String ?? ""
            let inputPrompt = entry["input"] as? String ?? ""
            let recordedAt = entry["recordedAt"] as? String ?? ""

            if (i + 1) % 50 == 0 || i == 0 {
                print("[\(i+1)/\(allEntries.count)] processing...")
            }

            guard FileManager.default.fileExists(atPath: audioPath) else {
                results.append(
                    makeResult(
                        index: idx, category: category, input: inputPrompt,
                        expected: expected, rawSTT: rawSTT, recordedAt: recordedAt,
                        baseline: nil, repaired: nil,
                        repairApplied: false, error: "audio not found"))
                errors += 1
                continue
            }

            do {
                let samples = try converter.resampleAudioFile(path: audioPath)

                // ── Baseline TDT ─────────────────────────────────────────
                let padded = manager.padAudioIfNeeded(samples, targetLength: ASRConstants.maxModelSamples)
                var state = TdtDecoderState.make()
                let (hypothesis, _) = try await manager.executeMLInferenceWithTimings(
                    padded,
                    originalLength: samples.count,
                    actualAudioFrames: nil,
                    decoderState: &state,
                    contextFrameAdjustment: 0,
                    isLastChunk: true
                )
                let baseline = manager.processTranscriptionResult(
                    tokenIds: hypothesis.ySequence,
                    timestamps: hypothesis.timestamps,
                    confidences: hypothesis.tokenConfidences,
                    encoderSequenceLength: 0,
                    audioSamples: samples,
                    processingTime: 0
                ).text

                // Raw token texts — used by viewer to reconstruct repaired string exactly
                let tokenTexts: [String] = hypothesis.ySequence.map { id in
                    vocab[id] ?? "<\(id)>"
                }

                // ── Find blank gaps ───────────────────────────────────────
                let ts = hypothesis.timestamps
                struct Gap {
                    let afterIdx: Int
                    let afterFrame: Int
                    let beforeFrame: Int
                    let gapFrames: Int
                }
                var gaps: [Gap] = []
                if ts.count >= 2 {
                    for gi in 0..<(ts.count - 1) {
                        let gf = ts[gi + 1] - ts[gi]
                        if gf >= Self.gapThresholdFrames {
                            gaps.append(Gap(afterIdx: gi, afterFrame: ts[gi], beforeFrame: ts[gi + 1], gapFrames: gf))
                        }
                    }
                }

                guard !gaps.isEmpty else {
                    results.append(
                        makeResult(
                            index: idx, category: category, input: inputPrompt,
                            expected: expected, rawSTT: rawSTT, recordedAt: recordedAt,
                            baseline: baseline, repaired: baseline,
                            repairApplied: false, error: nil))
                    continue
                }

                // ── Full-audio VAD ────────────────────────────────────────
                let fullVad = try await vad.process(samples)
                func hasSpeechInRange(t1: Double, t2: Double) -> (Bool, Float) {
                    var maxP: Float = 0
                    var active = false
                    for (ci, r) in fullVad.enumerated() {
                        let cs = Double(ci) * chunkDuration
                        let ce = cs + chunkDuration
                        guard cs <= t2 && ce >= t1 else { continue }
                        if r.probability > maxP { maxP = r.probability }
                        if r.isVoiceActive { active = true }
                    }
                    return (active, maxP)
                }

                // ── Per-gap: VAD check + isolated TDT for every gap candidate ──
                // We save full metadata so the viewer can apply different thresholds
                // without re-running inference.
                struct GapResult {
                    let afterTokenIdx: Int
                    let afterFrame: Int
                    let beforeFrame: Int
                    let gapFrames: Int
                    let vadMaxProb: Float
                    let hasSpeech: Bool
                    let recovered: String  // "" if TDT found nothing
                }

                var gapResults: [GapResult] = []
                for gap in gaps {
                    let gapT1 = Double(gap.afterFrame + 1) * Self.frameSeconds
                    let gapT2 = Double(gap.beforeFrame) * Self.frameSeconds
                    let (hasSpeech, vadProb) = hasSpeechInRange(t1: gapT1, t2: gapT2)

                    var recovered = ""
                    if hasSpeech {
                        let winStart = (gap.afterFrame + 3) * Self.samplesPerFrame
                        let winEnd = min((gap.beforeFrame + 2) * Self.samplesPerFrame, samples.count)
                        if winStart < samples.count && winStart < winEnd {
                            let winSamples = Array(samples[winStart..<winEnd])
                            let paddedWin = manager.padAudioIfNeeded(
                                winSamples, targetLength: ASRConstants.maxModelSamples)
                            var winState = TdtDecoderState.make()
                            let (winHyp, _) = try await manager.executeMLInferenceWithTimings(
                                paddedWin,
                                originalLength: winSamples.count,
                                actualAudioFrames: nil,
                                decoderState: &winState,
                                contextFrameAdjustment: 0,
                                isLastChunk: true
                            )
                            let winText = manager.processTranscriptionResult(
                                tokenIds: winHyp.ySequence,
                                timestamps: winHyp.timestamps,
                                confidences: winHyp.tokenConfidences,
                                encoderSequenceLength: 0,
                                audioSamples: winSamples,
                                processingTime: 0
                            ).text.trimmingCharacters(in: .whitespacesAndNewlines)
                            recovered = winText.trimmingCharacters(
                                in: CharacterSet.punctuationCharacters.union(.whitespaces))
                        }
                    }

                    gapResults.append(
                        GapResult(
                            afterTokenIdx: gap.afterIdx,
                            afterFrame: gap.afterFrame,
                            beforeFrame: gap.beforeFrame,
                            gapFrames: gap.gapFrames,
                            vadMaxProb: vadProb,
                            hasSpeech: hasSpeech,
                            recovered: recovered
                        ))
                }

                // Serialize gap results
                let gapData: [[String: Any]] = gapResults.map { g in
                    [
                        "afterTokenIdx": g.afterTokenIdx,
                        "afterFrame": g.afterFrame,
                        "beforeFrame": g.beforeFrame,
                        "gapFrames": g.gapFrames,
                        "vadMaxProb": Double(g.vadMaxProb),
                        "hasSpeech": g.hasSpeech,
                        "recovered": g.recovered,
                    ]
                }

                // Apply default threshold (8 frames) to compute the "repaired" baseline
                let defaultThreshold = 8
                var repairs: [Int: String] = [:]
                for g in gapResults where g.gapFrames >= defaultThreshold && !g.recovered.isEmpty {
                    repairs[g.afterTokenIdx] = g.recovered
                }

                var parts: [String] = []
                for (ti, tokenId) in hypothesis.ySequence.enumerated() {
                    let name = vocab[tokenId]?.replacingOccurrences(of: "▁", with: " ") ?? "<\(tokenId)>"
                    parts.append(name)
                    if let inserted = repairs[ti] {
                        parts.append(" \(inserted)")
                    }
                }
                let repaired = parts.joined()
                    .replacingOccurrences(of: "  ", with: " ")
                    .trimmingCharacters(in: .whitespaces)

                let didRepair = !repairs.isEmpty
                if didRepair { repairFired += 1 }

                let didChange = normalize(repaired) != normalize(baseline)
                if didChange { changed += 1 }

                var r = makeResult(
                    index: idx, category: category, input: inputPrompt,
                    expected: expected, rawSTT: rawSTT, recordedAt: recordedAt,
                    baseline: baseline, repaired: repaired,
                    repairApplied: didRepair, error: nil)
                r["gaps"] = gapData
                r["tokenTexts"] = tokenTexts
                r["tokenFrames"] = hypothesis.timestamps
                results.append(r)

            } catch {
                results.append(
                    makeResult(
                        index: idx, category: category, input: inputPrompt,
                        expected: expected, rawSTT: rawSTT, recordedAt: recordedAt,
                        baseline: nil, repaired: nil,
                        repairApplied: false, error: error.localizedDescription))
                errors += 1
            }
        }

        // ── Write output ─────────────────────────────────────────────────
        let summary: [String: Any] = [
            "total": allEntries.count,
            "repairFired": repairFired,
            "changed": changed,
            "errors": errors,
        ]
        let output: [String: Any] = ["summary": summary, "results": results]
        let data = try JSONSerialization.data(withJSONObject: output, options: [.sortedKeys])
        try data.write(to: URL(fileURLWithPath: Self.outputPath))

        print("\n=== SUMMARY ===")
        print("Total entries   : \(allEntries.count)")
        print("Repair fired    : \(repairFired)")
        print("Output changed  : \(changed)")
        print("Errors          : \(errors)")
        print("Written to      : \(Self.outputPath) (\(data.count / 1024)KB)")
    }

    private func normalize(_ s: String) -> String {
        s.lowercased().trimmingCharacters(in: .whitespacesAndNewlines)
    }

    private func makeResult(
        index: Int, category: String, input: String, expected: String,
        rawSTT: String, recordedAt: String,
        baseline: String?, repaired: String?,
        repairApplied: Bool, error: String?
    ) -> [String: Any] {
        var d: [String: Any] = [
            "index": index,
            "category": category,
            "input": input,
            "expected": expected,
            "rawSTT": rawSTT,
            "recordedAt": recordedAt,
            "baseline": baseline ?? "",
            "repaired": repaired ?? "",
            "repairApplied": repairApplied,
            "changed": (baseline != nil && repaired != nil && baseline != repaired),
        ]
        if let e = error { d["error"] = e }
        return d
    }
}
